import { Recommendation } from '../models';

export const INITIAL_RECOMMENDATIONS: Recommendation[] = [
  {
    id: 'rec-1',
    leadId: 'lead-4',
    company: 'Apex Cloud Systems',
    contact: 'Jennifer Ross',
    contactRole: 'VP Sales Strategy',
    aiScore: 94,
    probabilityPercentage: 87,
    action: 'Finalize legal terms and indemnification cap',
    reason: 'Quotation requested + demo completed + high engagement',
    urgency: 'immediate',
    category: 'Proposal',
    completed: false,
    lastTouch: 'Today, 8:40 AM'
  },
  {
    id: 'rec-2',
    leadId: 'lead-1',
    company: 'ABC Technologies',
    contact: 'David Sterling',
    contactRole: 'VP of Revenue Operations',
    aiScore: 91,
    probabilityPercentage: 86,
    action: 'Contact customer regarding quotation',
    reason: 'Quotation requested + repeated proposal engagement (4 views in 24h by CFO)',
    urgency: 'immediate',
    category: 'Contact',
    completed: false,
    lastTouch: 'Today, 10:32 AM'
  },
  {
    id: 'rec-3',
    leadId: 'lead-8',
    company: 'Veritas Financial',
    contact: 'Jonathan Wu',
    contactRole: 'Managing Director',
    aiScore: 92,
    probabilityPercentage: 88,
    action: 'Send final contract for DocuSign routing',
    reason: 'Discounts approved by sales VP; Jonathan confirmed budget authority up to $150k',
    urgency: 'immediate',
    category: 'Contact',
    completed: false,
    lastTouch: 'Today, 9:15 AM'
  },
  {
    id: 'rec-4',
    leadId: 'lead-2',
    company: 'TechCorp Solutions',
    contact: 'Elena Rostova',
    contactRole: 'CTO',
    aiScore: 87,
    probabilityPercentage: 82,
    action: 'Schedule decision-maker meeting',
    reason: 'Deep-dive demo completed + repeated responses from CTO and Security Architect',
    urgency: 'today',
    category: 'Demo',
    completed: false,
    lastTouch: 'Yesterday, 2:15 PM'
  },
  {
    id: 'rec-5',
    leadId: 'lead-14',
    company: 'OmniStream Analytics',
    contact: 'Tariq Al-Mansoor',
    contactRole: 'Chief Executive Officer',
    aiScore: 82,
    probabilityPercentage: 78,
    action: 'Send custom quotation proposal',
    reason: 'CEO attended demo and requested custom pricing for 40 seats with dedicated Slack channel',
    urgency: 'today',
    category: 'Proposal',
    completed: false,
    lastTouch: 'Today, 1:00 PM'
  },
  {
    id: 'rec-6',
    leadId: 'lead-6',
    company: 'QuantumSecure Labs',
    contact: 'Vikram Patel',
    contactRole: 'VP of Cybersecurity',
    aiScore: 84,
    probabilityPercentage: 80,
    action: 'Provision API test sandbox credentials',
    reason: 'Engineering team evaluated webhook architecture and asked for immediate sandbox access',
    urgency: 'today',
    category: 'Demo',
    completed: false,
    lastTouch: 'Today, 11:30 AM'
  },
  {
    id: 'rec-7',
    leadId: 'lead-3',
    company: 'Global Industries',
    contact: 'Marcus Vance',
    contactRole: 'Head of Global Procurement',
    aiScore: 74,
    probabilityPercentage: 68,
    action: 'Follow up with executive sponsor',
    reason: 'Proposal viewed 3 days ago but follow-up email has not been answered yet',
    urgency: 'today',
    category: 'Follow-up',
    completed: false,
    lastTouch: '3 days ago'
  },
  {
    id: 'rec-8',
    leadId: 'lead-11',
    company: 'AeroClean Dynamics',
    contact: 'Sophie Martens',
    contactRole: 'Chief Commercial Officer',
    aiScore: 64,
    probabilityPercentage: 58,
    action: 'Follow up on webinar Q&A data residency query',
    reason: 'Attended full 60-min webinar and submitted 2 technical queries regarding European compliance',
    urgency: 'this_week',
    category: 'Nurture',
    completed: false,
    lastTouch: '2 days ago'
  }
];
